# Generated by Django 4.1.1 on 2022-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0012_dosen_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='tanggal_lahir',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
