# Generated by Django 4.1.1 on 2022-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0016_dosen_fakultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='prodi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
